.libPaths("/ldfssz1/ST_OCEAN/USER/liaoshangfeng/software/anaconda3/envs/R411/lib/R/library/")
#suppressMessages(library(SingleCellExperiment,lib.loc="/ldfssz1/ST_OCEAN/USER/liaoshangfeng/software/anaconda3/envs/R4/lib/R/library"))
#suppressMessages(library(monocle3))
suppressMessages(library(Seurat))
#suppressMessages(library(SeuratWrappers))
suppressMessages(library(patchwork))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(spacexr))
library(viridis)
library(ggdark)

merge_lista <- vector()
merge_listb <- vector()

cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872D2','/','D01872D2','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872D2_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872D2_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','SS200000929BL_D2','/','SS200000929BL_D2','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("SS200000929BL_D2_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("SS200000929BL_D2_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01615B5','/','B01615B5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01615B5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01615B5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872D1','/','D01872D1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872D1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872D1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972D6','/','D01972D6','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972D6_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972D6_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972D1','/','D01972D1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972D1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972D1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872C5','/','D01872C5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872C5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872C5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872C4','/','D01872C4','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872C4_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872C4_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972D2','/','D01972D2','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972D2_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972D2_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972C1','/','D01972C1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972C1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972C1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972B6','/','D01972B6','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972B6_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972B6_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01615B1','/','B01615B1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01615B1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01615B1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872D3','/','D01872D3','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872D3_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872D3_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324E3','/','B02324E3','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324E3_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324E3_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324B5','/','B02324B5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324B5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324B5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01613C6','/','B01613C6','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01613C6_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01613C6_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324E4','/','B02324E4','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324E4_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324E4_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324A5','/','B02324A5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324A5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324A5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324A1','/','B02324A1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324A1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324A1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01613A5','/','B01613A5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01613A5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01613A5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01615B2','/','B01615B2','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01615B2_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01615B2_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01613B1','/','B01613B1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01613B1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01613B1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B02324E5','/','B02324E5','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B02324E5_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B02324E5_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01613D1','/','B01613D1','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01613D1_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01613D1_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872D4','/','D01872D4','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872D4_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872D4_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01972C4','/','D01972C4','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01972C4_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01972C4_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','D01872C6','/','D01872C6','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("D01872C6_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("D01872C6_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01613B2','/','B01613B2','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01613B2_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01613B2_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01317E6','/','B01317E6','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01317E6_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01317E6_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','B01615B3','/','B01615B3','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("B01615B3_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("B01615B3_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')

cat("Total_nFeature_Spatial",sep = '\n')
summary(merge_lista)
cat("Total_nCount_Spatial",sep = '\n')
summary(merge_listb)

