cellbin_data_file <- paste0('/zfssz2/ST_TSCBI/P22Z10200N0433/USER/wubin2/wubin2/pancnew/13.spa/05.cell_correct/result/','outfix_sample','/','outfix_sample','_cellbin.filter.rds')
cellbin_data <- readRDS(cellbin_data_file)
cellbin_data[["percent.mt"]] <- PercentageFeatureSet(cellbin_data, pattern = "^MT-")
data <- subset(cellbin_data, subset = nFeature_Spatial>100 & percent.mt < 15 & nFeature_Spatial<3000 & area>0 & area<2500)
cat("outfix_sample_nFeature_Spatial",sep = '\n')
summary(data$nFeature_Spatial)
merge_lista <- c(merge_lista, data$nFeature_Spatial)
cat("outfix_sample_nCount_Spatial",sep = '\n')
summary(data$nCount_Spatial)
merge_listb <- c(merge_listb, data$nCount_Spatial)
cat('The number of cellbin:','\n',ncol(data),'\n')
